### ISSUE TITLE
bug: built files (dist) doesnt work

### ISSUE THREAD

**Issue by flipjs** [cafreeman/generator-mobx-react#2]
Built files produced by either `npm run build` or `npm run compile` throws an error in the browser:

`
Uncaught Error: locals[0] does not appear to be a`module`object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using`env`section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
`

**Comment by cafreeman** [comment]
@flipjs Thanks for catching that! Looks like I got a little carried away with the copy/paste, but it should be fixed now :)

**Comment by flipjs** [comment]
@cafreeman , yes it is fixed now. I like that webpack config has option for hash/chunkhash in the output section, which you commented out. I tried it and it works too. Thanks!
