### ISSUE TITLE
Hash files on build?

### ISSUE THREAD

**Issue by flipjs** [cafreeman/generator-mobx-react#4]
It would be nice if the build files are hashed on build. Or it could be switched on by default and generate sourcemap on development.

**Comment by cafreeman** [comment]
These both seem doable. I currently have the hashing option written into the config, it's just commented out because I wasn't sure if people would want it or not.

Wouldn't be hard to make that an option. I'll take a look at it and the sourcemap today.

**Comment by cafreeman** [comment]
Just added hashing/chunking by default in the build step :)

In dev mode, webpack now generates full source maps as well so you should be good to go!
